server.address=0.0.0.0
server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://osi-ltsd-svr.mysql.database.azure.com:3306/lumileaf_system
spring.datasource.username=zbzqbabxgz
spring.datasource.password=Ystp$1NYCd4nL5te
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.base-url=https://lum-leaf-etdvaha9d9h4h4fx.southeastasia-01.azurewebsites.net
server.error.include-message=always
server.error.include-stacktrace=always
spring.thymeleaf.cache=false

logging.file.path=/home/LogFiles/Application
